name: "Whiskin' Sugar"
favicon: null
layout_spectrum: 0.1359132097568363
typography_spectrum: 0.6027235635556281
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5800681430846453
  lightness: 0.6568124883342534
  saturation: 0.8556388441938907
  rhythmicContrast: 0.23066353192552924
purpose: []
